### ISSUE TITLE
[pzztool.py] Todo for 0.15.0

### ISSUE THREAD

**Issue by GGLinnk** [Virtual-World-RE/NeoGF#1]
# pzztool.py
- [ ] Implement ``-di`` everywhere.
- [x] Add a "counter" in the tests.
- [ ] Remove trailing Null byte when decompressing .arz
