### ISSUE TITLE
[doltool.py] Todo for 0.1.0

### ISSUE THREAD

**Issue by tmpz23** [Virtual-World-RE/NeoGF#10]
# doltool.py
- [x] Add mask for first byte 01FFFFFF to get address (and allow 03 and 05 in regex)
- [x] Control patching length to avoid dol segment overflow on next segment.
- [x] Add tests for --patch-action-replay
- [ ] Add standard comments
- [x] Add system to patch out "not in existing sections space" action replay codes:
    - [x]  Add an --analyse-action-replay command to show stats on the file and memory section to add if not in already mapped virtual space
    - [x] Add -sr command to add automaticly new section for unmapped arcodes
    - [ ] Add tests on -sr command
- [ ] Add a --add-section command to allow adding a Null initialised .data or .text section usefull for -par command
- [ ] Add a command to parse addresses with data dump as hex for patching.
