### ISSUE TITLE
Todo for 0.1.0

### ISSUE THREAD

**Issue by tmpz23** [Virtual-World-RE/NeoGF#6]
# afstool.py
- [x] Add the documentation on the main md.
- [x] Implement `--stats` command.
- [x] Implement `--pack` with updating of files in the AFS using next file offset.
- [x] Implement `--rebuild` using afs_rebuild.conf autogenerated file.

# afstest.py
- [x] Add full `--pack` 
- [x] Add full `--rebuild` tests.

**Comment by tmpz23** [comment]
Using decimal representation in stats doesn't make sens for offsets / length. Only hex is used and this avoid complex formating since all big numbers can be represented in 8 digits.
Unpack should handle file unpack when they use the same filename:
-Solution is to use a filename_resolver.csv file to match file index and new name when unpacked. The packed filename is used only when we rebuild filesys using afs_rebuild.csv.
-filename_resolver.csv can now be used to change names when there is no FD (no names for files) just by adding a line with index, unpacked_filename

**Comment by tmpz23** [comment]
Rebuild sys should use a conf file to set the AFS files (and sys files) offsets map according to the need of the dol and his specific AFS parser.
