### ISSUE TITLE
[afstool.py] Todo for 0.2.0

### ISSUE THREAD

**Issue by tmpz23** [Virtual-World-RE/NeoGF#8]
# afstool.py
- [x] Add standard comments
- [x] Security enhancement - restrict files extraction on root folder only
- [x] Fix FD name handling - add folder creation and path operators (G2GJB2 - Gundam JAP)
