### ISSUE TITLE
[gcmtool.py] Todo for 0.2.0

### ISSUE THREAD

**Issue by tmpz23** [Virtual-World-RE/NeoGF#9]
# gcmtool.py
- [x] Add custom exceptions and tests for it
- [x] Add pack collision detection system
    - [x] apploader size overflow
    - [x] dol size overflow
    - [x] fst size overflow 
- [x] Add standard comments
- [x] Add commands & stats for patching GCM system infos: (.ini / conf file ?)
    - [x] boot.bin: (disk header)
        - [x] gamecode: consoleId / GameCode / CountryCode
        - [x] maker code
        - [x] disk number
        - [x] game version
        - [x] audio streaming flag
        - [x] stream buffer size
        - [x] DVDMagicWord
        - [x] game Name
        - [x] dol offset
        - [x] fst offset
        - [x] fst len
        - [x] fst max len
        - [x] user position
        - [x] user length
    - [x] bi2.bin: (disc header information)
        - [x] debug-monitor Size
        - [x] Simulated Memory Size
        - [x] Argument offset
        - [x] Debug flag
        - [x] Track location
        - [x] Track size
        - [x] country code
        - [x] total disks
        - [x] longFileNameSupport
        ~~padSpec ?~~
        - [x] dollimit (4MB - unlimited)
    - [x] apploader
        - [x] version
        - [x] entry point
        - [x] size
        - [x] trailer size
- [x] Add system.conf documentation with formats and limits
- [x] Rebuild fst command
    - [x] Add conf handling
    - [x] Add user position and user length patch

**Comment by tmpz23** [comment]
It's unclear if bi2.bin concern track (location, size) or Target Resident Kernel (location, size).
Dollimit has to be tested by restricting it to a value < dol len. So the apploader should trigger an error.
